image: cxx

stages:
  - build
  - test

build:
  stage: build
  tags:
    - shared-fi
  script:
    - cmake -Bbuild tests/
    - make -Cbuild -j
  artifacts:
    untracked: true

test:
  stage: test
  tags:
    - shared-fi
  script:
    - cd build && ctest
  dependencies:
    - build

