image: cxx

stages:
  - test

test_bare:
  stage: test
  tags:
    - shared-fi
  script:
    - make_test

test_address:
  stage: test
  tags:
    - shared-fi
  script:
    - make test SANITIZER=address

test_undefined:
  stage: test
  tags:
    - shared-fi
  script:
    - make test SANITIZER=undefined

